/// Golden tests for `lib/inference/strength.dart`.
///
/// Reads `assets/golden/strength_golden.json` (generated by
/// `tools/tflite_export/gen_strength_golden.py`) and verifies every Dart
/// function reproduces the Python output bit-for-bit (within FP tolerance).
library;

import 'dart:convert';
import 'dart:io';

import 'package:deepgain_app/inference/strength.dart';
import 'package:flutter_test/flutter_test.dart';

/// FP tolerance: Python casts intermediate weighted averages to np.float32
/// (~1.2e-7 eps), Dart uses float64 throughout. The resulting divergence
/// after a few multiplications is ~1e-5 — still negligible for kg-scale 1RM.
const double kTol = 1e-5;

StrengthPriors _loadPriors() {
  final raw = jsonDecode(
    File('assets/model/strength_priors.json').readAsStringSync(),
  ) as Map<String, dynamic>;
  return StrengthPriors.fromJson(raw);
}

Map<String, dynamic> _loadGolden() {
  return jsonDecode(File('assets/golden/strength_golden.json').readAsStringSync())
      as Map<String, dynamic>;
}

void _expectAnchorsClose(List<double> actual, List<double> expected,
    {String? reason}) {
  expect(actual.length, expected.length, reason: reason);
  for (var i = 0; i < expected.length; i++) {
    expect((actual[i] - expected[i]).abs(), lessThan(kTol),
        reason: '$reason (idx $i: expected ${expected[i]}, got ${actual[i]})');
  }
}

void main() {
  late StrengthPriors priors;
  late Map<String, dynamic> golden;

  setUpAll(() {
    priors = _loadPriors();
    golden = _loadGolden();
  });

  group('coerceAnchorValues', () {
    test('matches Python golden for all input shapes', () {
      for (final raw in (golden['coerce'] as List)) {
        final c = raw as Map<String, dynamic>;
        final actual = priors.coerceAnchorValues(c['input']);
        final expected = List<double>.from(
            (c['expected'] as List).map((v) => (v as num).toDouble()));
        _expectAnchorsClose(actual, expected, reason: c['name'] as String);
      }
    });
  });

  group('projectExercise1rmKg', () {
    test('matches Python golden across exercises', () {
      for (final raw in (golden['project'] as List)) {
        final c = raw as Map<String, dynamic>;
        final exercise = c['exercise'] as String;
        final actual = priors.projectExercise1rmKg(
          exercise,
          anchorValues: c['anchors_kg'],
        );
        final expected = c['expected'];
        if (expected == null) {
          expect(actual, isNull, reason: 'exercise=$exercise expected null');
        } else {
          expect(actual, isNotNull, reason: 'exercise=$exercise');
          expect((actual! - (expected as num).toDouble()).abs(),
              lessThan(kTol),
              reason: 'exercise=$exercise');
        }
      }
    });
  });

  group('estimateE1rmCandidate', () {
    test('matches Python golden including invalid input null path', () {
      for (final raw in (golden['e1rm'] as List)) {
        final c = raw as Map<String, dynamic>;
        final actual = priors.estimateE1rmCandidate(
          (c['weight_kg'] as num).toDouble(),
          (c['reps'] as num).toInt(),
          (c['rir'] as num).toDouble(),
        );
        final expected = c['expected'];
        if (expected == null) {
          expect(actual, isNull,
              reason: 'w=${c['weight_kg']} r=${c['reps']} rir=${c['rir']} '
                  'should be null');
        } else {
          expect(actual, isNotNull);
          expect((actual! - (expected as num).toDouble()).abs(),
              lessThan(kTol));
        }
      }
    });
  });

  group('updateStrengthAnchors', () {
    test('matches Python golden across update scenarios', () {
      for (final raw in (golden['update'] as List)) {
        final c = raw as Map<String, dynamic>;
        final completed = (c['completed_sets'] as List)
            .map((e) => Map<String, dynamic>.from(e as Map))
            .toList();
        final actual = priors.updateStrengthAnchors(
          c['anchors_kg'], completed,
        );
        final expected = List<double>.from((c['expected_new_anchors'] as List)
            .map((v) => (v as num).toDouble()));
        _expectAnchorsClose(actual, expected, reason: c['name'] as String);
      }
    });
  });

  group('buildAnchorHistoryFromCompletedSets', () {
    test('matches Python golden for multi-session replay', () {
      for (final raw in (golden['history'] as List)) {
        final c = raw as Map<String, dynamic>;
        final completed = (c['completed_sets'] as List)
            .map((e) => Map<String, dynamic>.from(e as Map))
            .toList();
        final result = priors.buildAnchorHistoryFromCompletedSets(
          c['anchors_kg'], completed,
        );

        final expectedHistory = (c['expected_history'] as List)
            .map((row) =>
                List<double>.from((row as List).map((v) => (v as num).toDouble())))
            .toList();
        expect(result.history.length, expectedHistory.length,
            reason: '${c['name']} history length');
        for (var i = 0; i < expectedHistory.length; i++) {
          _expectAnchorsClose(result.history[i], expectedHistory[i],
              reason: '${c['name']} step $i');
        }

        final expectedFinal = List<double>.from(
            (c['expected_final'] as List).map((v) => (v as num).toDouble()));
        _expectAnchorsClose(result.finalAnchors, expectedFinal,
            reason: '${c['name']} final');
      }
    });
  });
}
