/// Integration tests: run KnapsackPlanner against `assets/golden/planner_golden.json`
/// (generated by `tools/tflite_export/gen_planner_golden.py`) and verify the
/// Dart plan matches the Python plan block-by-block.
///
/// Requires libtensorflowlite_c-mac.dylib (see test/README.md). The DP / eval
/// unit tests in `knapsack_dp_test.dart` are the host-runnable subset.
library;

import 'dart:convert';
import 'dart:io';

import 'package:deepgain_app/inference/deepgain.dart';
import 'package:deepgain_app/inference/model_assets.dart';
import 'package:deepgain_app/inference/strength.dart';
import 'package:deepgain_app/inference/types.dart';
import 'package:deepgain_app/planner/knapsack_planner.dart';
import 'package:deepgain_app/planner/planner_meta.dart';
import 'package:flutter_test/flutter_test.dart';

const double kWeightTol = 1e-2;
const double kRirTol = 5e-3;
const double kMpcTol = 1e-3;
const double kStimulusTol = 1e-4;

Future<ModelAssets> _loadAssetsFromDisk() async {
  final dir = Directory('assets/model');
  Map<String, dynamic> j(String n) => jsonDecode(
      File('${dir.path}/$n').readAsStringSync()) as Map<String, dynamic>;
  List<dynamic> jl(String n) => jsonDecode(
      File('${dir.path}/$n').readAsStringSync()) as List<dynamic>;

  final exercises = List<String>.from(jl('exercises.json'));
  final muscles = List<String>.from(jl('muscles.json'));
  final inv = jl('involvement_matrix.json')
      .map((row) => List<double>.from(
          (row as List).map((v) => (v as num).toDouble())))
      .toList(growable: false);
  final anchor = j('anchor_ratio_matrix.json');
  final ratios = (anchor['ratios'] as List)
      .map((row) => List<double>.from(
          (row as List).map((v) => (v as num).toDouble())))
      .toList(growable: false);
  final availability = List<double>.from(
      (anchor['available'] as List).map((v) => (v as num).toDouble()));
  final tau = List<double>.from(
      jl('fixed_tau.json').map((v) => (v as num).toDouble()));
  final scalesRaw = j('scales.json');
  final scales = Scales(
    weight: (scalesRaw['WEIGHT_SCALE'] as num).toDouble(),
    reps: (scalesRaw['REPS_SCALE'] as num).toDouble(),
    rir: (scalesRaw['RIR_SCALE'] as num).toDouble(),
    dt: (scalesRaw['DT_SCALE'] as num).toDouble(),
  );
  final defaults = j('default_anchors_kg.json');
  final defaultAnchorsKg = List<double>.from(
      (defaults['values_kg'] as List).map((v) => (v as num).toDouble()));

  return ModelAssets.fromRaw(
    fNetBytes: File('${dir.path}/f_net.tflite').readAsBytesSync(),
    gNetBytes: File('${dir.path}/g_net.tflite').readAsBytesSync(),
    exercises: exercises,
    muscles: muscles,
    involvement: inv,
    anchorRatios: ratios,
    anchorAvailable: availability,
    tau: tau,
    scales: scales,
    defaultAnchorsKg: defaultAnchorsKg,
  );
}

void main() {
  late ModelAssets assets;
  late DeepGain dg;
  late StrengthPriors priors;
  late PlannerMeta meta;
  final fixtures = jsonDecode(
    File('assets/golden/planner_golden.json').readAsStringSync(),
  ) as List;

  setUpAll(() async {
    assets = await _loadAssetsFromDisk();
    dg = DeepGain.fromAssets(assets);
    priors = StrengthPriors.fromJson(jsonDecode(
      File('assets/model/strength_priors.json').readAsStringSync(),
    ) as Map<String, dynamic>);
    meta = PlannerMeta.fromJson(jsonDecode(
      File('assets/model/planner_meta.json').readAsStringSync(),
    ) as Map<String, dynamic>);
  });

  tearDownAll(() => assets.close());

  for (final scenarioRaw in fixtures) {
    final sc = scenarioRaw as Map<String, dynamic>;
    final name = sc['name'] as String;

    test('planner: $name', () {
      final history = (sc['history'] as List)
          .map((h) => WorkoutSet.fromJson(h as Map<String, dynamic>))
          .toList();
      final anchors = sc['anchors_kg'] as Map<String, dynamic>;
      final exclusions = Set<String>.from(
          (sc['exclusions'] as List).map((e) => e as String));
      final now = DateTime.parse(sc['now'] as String);

      final planner = KnapsackPlanner(
        deepgain: dg, strengthPriors: priors, meta: meta,
        strengthAnchors: anchors,
      );
      final plan = planner.plan(
        userHistory: history,
        timeBudgetSec: (sc['time_budget_sec'] as num).toInt(),
        targetRir: (sc['target_rir'] as num).toInt(),
        exclusions: exclusions,
        now: now,
      );

      final expectedBlocks = (sc['expected_blocks'] as List)
          .map((b) => b as Map<String, dynamic>)
          .toList();

      // Same exercises in same order.
      expect(
        plan.blocks.map((b) => b.exerciseId).toList(),
        expectedBlocks.map((b) => b['exercise_id'] as String).toList(),
        reason: '$name: block sequence',
      );

      // Per-block field match.
      for (var i = 0; i < expectedBlocks.length; i++) {
        final exp = expectedBlocks[i];
        final got = plan.blocks[i];
        expect(got.weightKg, closeTo((exp['weight_kg'] as num).toDouble(), kWeightTol),
            reason: '$name[$i] weight_kg');
        expect(got.reps, exp['reps'], reason: '$name[$i] reps');
        expect(got.setsCount, exp['sets_count'], reason: '$name[$i] sets_count');
        expect(got.predictedRir,
            closeTo((exp['predicted_rir'] as num).toDouble(), kRirTol),
            reason: '$name[$i] predicted_rir');
        expect(got.timeCostSec, exp['time_cost_sec'], reason: '$name[$i] time_cost_sec');
        expect(got.exType, exp['ex_type'], reason: '$name[$i] ex_type');
        expect(got.stimulusScore,
            closeTo((exp['stimulus_score'] as num).toDouble(), kStimulusTol),
            reason: '$name[$i] stimulus_score');
      }

      expect(plan.totalTimeSec, sc['expected_total_time_sec'],
          reason: '$name total_time_sec');

      // MPC before/after — every muscle within tolerance.
      for (final entry
          in (sc['expected_mpc_before'] as Map<String, dynamic>).entries) {
        final got = plan.mpcBefore[entry.key];
        expect(got, isNotNull);
        expect((got! - (entry.value as num).toDouble()).abs(),
            lessThan(kMpcTol),
            reason: '$name mpc_before[${entry.key}]');
      }
      for (final entry
          in (sc['expected_mpc_after'] as Map<String, dynamic>).entries) {
        final got = plan.mpcAfter[entry.key];
        expect(got, isNotNull);
        expect((got! - (entry.value as num).toDouble()).abs(),
            lessThan(kMpcTol),
            reason: '$name mpc_after[${entry.key}]');
      }
    });
  }
}
