/// Planner metadata loaded from `assets/model/planner_meta.json`
/// (generated by `tools/tflite_export/gen_planner_assets.py`).
///
/// Mirrors the constants defined at the top of `knapsack_planner.py`:
///   - MUSCLE_INVOLVEMENT (per-exercise muscle engagement ratios)
///   - EXERCISE_META (sets/reps/set_sec/intensity per exercise)
///   - MAIN_EXERCISES (compound triumvirate variants)
///   - DEFAULT_TARGET_ZONES (per-muscle MPC bounds after the session)
library;

import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

class ExerciseMeta {
  /// 'compound' / 'variation' / 'isolation' / 'core'
  final String type;
  final int sets;

  /// Candidate rep counts (knapsack picks one). The current planner pins
  /// reps to FIXED_REPS=10 regardless, but the field is preserved for
  /// future tuning.
  final List<int> reps;

  /// Estimated time per set in seconds (excluding rest).
  final int setSec;

  /// % of 1RM used as default training intensity. The planner overrides
  /// this with binary search on predict_rir, but it's the starting point
  /// for the search and the fixed weight for bodyweight exercises.
  final double intensity;

  const ExerciseMeta({
    required this.type,
    required this.sets,
    required this.reps,
    required this.setSec,
    required this.intensity,
  });

  factory ExerciseMeta.fromJson(Map<String, dynamic> j) => ExerciseMeta(
        type: j['type'] as String,
        sets: (j['sets'] as num).toInt(),
        reps: List<int>.from((j['reps'] as List).map((v) => (v as num).toInt())),
        setSec: (j['set_sec'] as num).toInt(),
        intensity: (j['intensity'] as num).toDouble(),
      );
}

class PlannerMeta {
  /// muscleInvolvement[exerciseId][muscleId] = engagement ratio in (0, 1].
  /// Missing entries are zero engagement.
  final Map<String, Map<String, double>> muscleInvolvement;
  final Map<String, ExerciseMeta> exerciseMeta;
  final Set<String> mainExercises;

  /// targetZones[muscleId] = [min_after, max_after] for the post-session MPC.
  final Map<String, List<double>> targetZones;

  /// Fallback kg used when an exercise has no anchor (bodyweight) and the
  /// model can't project a 1RM.
  final double bodyweightFallbackKg;

  const PlannerMeta({
    required this.muscleInvolvement,
    required this.exerciseMeta,
    required this.mainExercises,
    required this.targetZones,
    required this.bodyweightFallbackKg,
  });

  static Future<PlannerMeta> load({
    String path = 'assets/model/planner_meta.json',
  }) async {
    return PlannerMeta.fromJson(jsonDecode(await rootBundle.loadString(path))
        as Map<String, dynamic>);
  }

  factory PlannerMeta.fromJson(Map<String, dynamic> raw) {
    final inv = <String, Map<String, double>>{};
    for (final entry in (raw['muscle_involvement'] as Map<String, dynamic>).entries) {
      inv[entry.key] = {
        for (final m in (entry.value as Map<String, dynamic>).entries)
          m.key: (m.value as num).toDouble(),
      };
    }

    final meta = <String, ExerciseMeta>{};
    for (final entry in (raw['exercise_meta'] as Map<String, dynamic>).entries) {
      meta[entry.key] = ExerciseMeta.fromJson(entry.value as Map<String, dynamic>);
    }

    final main = Set<String>.from(raw['main_exercises'] as List);

    final zones = <String, List<double>>{};
    for (final entry in (raw['default_target_zones'] as Map<String, dynamic>).entries) {
      zones[entry.key] = List<double>.from(
          (entry.value as List).map((v) => (v as num).toDouble()));
    }

    return PlannerMeta(
      muscleInvolvement: inv,
      exerciseMeta: meta,
      mainExercises: main,
      targetZones: zones,
      bodyweightFallbackKg: (raw['bodyweight_fallback_kg'] as num).toDouble(),
    );
  }
}
